/**
 * Ask AI's question interpreter.
 *
 * Turns a question - and the conversation so far - into an answer built from
 * structured blocks: a metric, a patient list, a group comparison, a method,
 * the SQL behind it. Every number comes from lib/cohort.ts, the same functions
 * Home, Care Gaps, Patients and Analytics use, so an answer here cannot
 * disagree with the rest of the app. Nothing is generated by a language model:
 * the site is a static export with no server, so the interpretation is rules,
 * and anything the rules do not recognise gets an honest "I can't answer that"
 * with suggestions rather than a guess.
 *
 * Context carries the population last discussed, so "how many of them were
 * seen recently?" narrows the previous answer instead of starting over, and
 * "how did you calculate that?" or "show me the SQL" explain the previous
 * answer rather than a new one.
 *
 * Pure (no storage, no fetch), so `node --test` checks it against the gold
 * report, and every SQL string it emits is checked against DuckDB.
 */

import type { PatientRow } from "../data";
import type { PatientDetail } from "../patientDetail";
import type { AgeBand, GroupRow, StatusFilter } from "../cohort.ts";
import {
  daysOverdue, filterPatients, gapStatus, lastA1cValue, monitoringByAgeBand, monitoringBySetting,
  monthsBefore, pctText, settingLabel, shortMrn, sortPatients,
} from "../cohort.ts";
import { longDate } from "../dates.ts";

/* ------------------------------------------------------------------ types */

export type Pop = {
  status: StatusFilter;
  band: AgeBand | "all";
  setting: string;
  insulin: "all" | "yes" | "no";
  /** Last encounter within this many months of the data date. */
  seenMonths: number | null;
};

export const ALL_PATIENTS: Pop = { status: "all", band: "all", setting: "all", insulin: "all", seenMonths: null };

export type Block =
  | { kind: "text"; text: string }
  | { kind: "metric"; value: string; label: string; detail?: string }
  /** Patient ids only; rows are rendered from the source data at display time. */
  | { kind: "patients"; ids: string[] }
  | { kind: "groups"; dimension: "age" | "setting"; rows: GroupRow[]; highlight?: string; small: number }
  | { kind: "years"; rows: { year: string; tests: number; patients: number }[]; partial: string[] }
  | { kind: "patient"; id: string }
  | { kind: "links"; links: { href: string; label: string }[] }
  | { kind: "method"; items: { label: string; value: string }[] }
  | { kind: "sql"; sql: string; note: string }
  | { kind: "limitation"; text: string }
  | { kind: "suggestions"; items: string[] };

export type Ctx = {
  pop?: Pop;
  /** The population the last answer was a share of, for "of them" denominators. */
  parent?: Pop;
  patientId?: string;
  method?: { label: string; value: string }[];
  sql?: string;
  /** What the last answer was, so "show them" knows to list. */
  last?: "count" | "list" | "percent" | "groups" | "years" | "patient" | "explain" | "none";
};

export type Data = {
  rows: PatientRow[];
  asof: string;
  /** Per-patient history, only needed for testing-over-time questions. */
  history?: Record<string, PatientDetail>;
};

export type Answer = { blocks: Block[]; ctx: Ctx; title?: string };
export type Result = Answer | { needs: "history" };

/* ------------------------------------------------------------- vocabulary */

const SMALL = 10;

const WORD_NUM: Record<string, number> = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10,
  eleven: 11, twelve: 12, eighteen: 18, "twenty-four": 24,
};

const SETTING_WORDS: [RegExp, string][] = [
  [/\bambulatory\b/, "ambulatory"],
  [/\boutpatient\b/, "outpatient"],
  [/\bwellness\b/, "wellness"],
  [/\burgent ?care\b/, "urgentcare"],
  [/\bemergency\b|\b(the )?er\b|\bed\b/, "emergency"],
  [/\bskilled nursing\b|\bsnf\b|\bnursing (home|facility)\b/, "snf"],
  [/\bhospice\b/, "hospice"],
];

const BAND_WORDS: [RegExp, AgeBand][] = [
  [/\b18\s*(-|–|to)\s*44\b|\bunder 45\b|\byounger than 45\b/, "18-44"],
  [/\b45\s*(-|–|to)\s*64\b/, "45-64"],
  [/\b65\s*(-|–|to)\s*75\b/, "65-75"],
  [/\b76\s*\+|\b76 and (over|older)\b|\bover 75\b|\bolder than 75\b|\b76 or older\b/, "76+"],
];

const BAND_LABEL = (b: AgeBand) => (b === "76+" ? "76+" : b.replace("-", "–"));

/* -------------------------------------------------------------- parsing */

const has = (q: string, re: RegExp) => re.test(q);

function parseStatus(q: string): StatusFilter | null {
  if (has(q, /never (been )?(tested|had)|no (recorded )?a1c|without (an |any )?a1c|untested|not been tested|no result/)) return "never";
  if (has(q, /\boverdue\b/) && !has(q, /most overdue|longest overdue/)) return "overdue";
  if (has(q, /\bcurrent\b|up[- ]to[- ]date/)) return "current";
  if (has(q, /open (a1c )?(monitoring )?gaps?|care gaps?|\bwith (a|an open) gap|have (a|an open) gap|\bgaps?\b/)) return "gap";
  return null;
}

function parseSeen(q: string): number | null {
  const m = q.match(/seen (?:in |within )?(?:the )?(?:last|past) (\d+|[a-z-]+) months?/);
  if (m) {
    const n = Number(m[1]) || WORD_NUM[m[1]];
    if (n) return n;
  }
  if (has(q, /seen (in the last year|in the past year|within a year)/)) return 12;
  if (has(q, /seen recently|recently seen|recent (visit|encounter)|seen lately/)) return 6;
  return null;
}

function parsePop(q: string): Partial<Pop> {
  const p: Partial<Pop> = {};
  const status = parseStatus(q);
  if (status) p.status = status;
  for (const [re, b] of BAND_WORDS) if (re.test(q)) p.band = b;
  for (const [re, s] of SETTING_WORDS) if (re.test(q)) p.setting = s;
  if (has(q, /not on insulin|without insulin|no (active )?insulin/)) p.insulin = "no";
  else if (has(q, /insulin/)) p.insulin = "yes";
  const seen = parseSeen(q);
  if (seen) p.seenMonths = seen;
  return p;
}

const isFollowUp = (q: string) =>
  has(q, /\b(them|those|these|they|that group|this group|same patients|of them|among them)\b/) ||
  has(q, /^(and|what about|how about|and what about|of those|of these)\b/);

/* --------------------------------------------------------- populations */

function popRows(rows: PatientRow[], p: Pop, asof: string): PatientRow[] {
  const base = filterPatients(rows, { status: p.status, query: "", setting: p.setting, band: p.band, insulin: p.insulin });
  if (!p.seenMonths) return base;
  const since = monthsBefore(asof, p.seenMonths);
  return base.filter((r) => r.last_encounter_date && String(r.last_encounter_date) >= since);
}

/** The population in words: "patients aged 45–64 with an open A1c gap, seen in the last 6 months". */
export function describePop(p: Pop): string {
  const status: Record<StatusFilter, string> = {
    all: "patients",
    current: "current patients",
    gap: "patients with an open A1c gap",
    never: "never-tested patients",
    overdue: "overdue patients",
  };
  const parts = [status[p.status]];
  if (p.band !== "all") parts.push(`aged ${BAND_LABEL(p.band)}`);
  if (p.setting !== "all") parts.push(`last seen in ${settingLabel(p.setting).toLowerCase()}`);
  if (p.insulin === "yes") parts.push("with active insulin documented");
  if (p.insulin === "no") parts.push("with no active insulin documented");
  if (p.seenMonths) parts.push(`seen in the last ${p.seenMonths} months`);
  return parts.join(", ").replace(/, (aged|with|last seen)/g, " $1");
}

const STATUS_DEFS: Record<StatusFilter, string | null> = {
  all: null,
  current: "Current: an A1c result within the 365 days before the data date.",
  gap: "Open A1c gap: no A1c result in the 365 days before the data date, including patients with no result at all.",
  never: "Never tested: no A1c result anywhere in the available data. Every never-tested patient has an open gap.",
  overdue: "Overdue: an earlier A1c result, but none in the 365 days before the data date.",
};

function method(p: Pop, n: number, of: number, ofLabel: string, asof: string, total: number) {
  const filters: string[] = [];
  if (p.status !== "all") filters.push(STATUS_DEFS[p.status]!);
  if (p.band !== "all") filters.push(`Age band ${BAND_LABEL(p.band)}, the measure's age boundaries.`);
  if (p.setting !== "all") filters.push(`Care setting of the last encounter: ${settingLabel(p.setting)}.`);
  if (p.insulin === "yes") filters.push("An insulin prescription active on the data date is documented.");
  if (p.insulin === "no") filters.push("No insulin prescription active on the data date is documented.");
  if (p.seenMonths) filters.push(`Last encounter on or after ${longDate(monthsBefore(asof, p.seenMonths))} (${p.seenMonths} months before the data date).`);
  return [
    { label: "Population", value: `All ${total} patients in the diabetes cohort, alive on the data date (${longDate(asof)}).` },
    { label: "Filters", value: filters.length ? filters.join(" ") : "None." },
    { label: "Result", value: `${n} ${n === 1 ? "patient" : "patients"}.` },
    { label: "Denominator", value: `${of} ${ofLabel}.` },
    { label: "Source", value: "The same care-gap fields Home, Care Gaps, Patients and Analytics use, computed by the data pipeline." },
  ];
}

/** The SQL equivalent of a population, against the `patients` view of the
 *  exported report. Verified against DuckDB in the test suite's companion check. */
export function popSql(p: Pop, asof: string, mode: "count" | "list"): string {
  const where: string[] = [];
  if (p.status === "gap") where.push("gap_flag");
  if (p.status === "current") where.push("NOT gap_flag");
  if (p.status === "never") where.push("last_a1c_date IS NULL");
  if (p.status === "overdue") where.push("gap_flag AND last_a1c_date IS NOT NULL");
  if (p.band === "18-44") where.push("age < 45");
  if (p.band === "45-64") where.push("age BETWEEN 45 AND 64");
  if (p.band === "65-75") where.push("age BETWEEN 65 AND 75");
  if (p.band === "76+") where.push("age >= 76");
  if (p.setting !== "all") where.push(`unit = '${p.setting.replace(/'/g, "''")}'`);
  if (p.insulin === "yes") where.push("on_insulin");
  if (p.insulin === "no") where.push("NOT on_insulin");
  if (p.seenMonths) where.push(`last_encounter_date >= DATE '${asof}' - INTERVAL ${p.seenMonths} MONTH`);
  const w = where.length ? `\nWHERE ${where.join("\n  AND ")}` : "";
  return mode === "count"
    ? `SELECT count(*) AS patients\nFROM patients${w}`
    : `SELECT mrn, age, last_a1c_date, last_a1c_value, days_overdue,\n       last_encounter_date, unit\nFROM patients${w}\nORDER BY priority NULLS LAST, mrn`;
}

/** Links into the operational pages that show the same population, where
 *  their URL filters can express it. */
function popLinks(p: Pop): { href: string; label: string }[] {
  const links: { href: string; label: string }[] = [];
  if (!p.seenMonths) {
    const qs = new URLSearchParams();
    if (p.status !== "all") qs.set("status", p.status);
    if (p.band !== "all") qs.set("age", p.band);
    if (p.setting !== "all") qs.set("setting", p.setting);
    if (p.insulin !== "all") qs.set("insulin", p.insulin);
    const s = qs.toString();
    links.push({ href: `/patients${s ? `?${s}` : ""}`, label: "View in Patients" });
  }
  if ((p.status === "never" || p.status === "overdue" || p.status === "gap") &&
      p.band === "all" && p.setting === "all" && p.insulin === "all" && !p.seenMonths) {
    links.push({ href: p.status === "gap" ? "/care-gaps" : `/care-gaps?status=${p.status}`, label: "View all in Care Gaps" });
  }
  return links;
}

/* ------------------------------------------------------------- answers */

function basis(asof: string) {
  return `Based on the available A1c results through ${longDate(asof)}.`;
}

function populationAnswer(
  pop: Pop, mode: "count" | "list" | "percent", data: Data, parent: Pop | undefined,
): Answer {
  const rows = popRows(data.rows, pop, data.asof);
  const n = rows.length;
  const parentRows = parent ? popRows(data.rows, parent, data.asof) : data.rows;
  const of = parentRows.length;
  const ofLabel = parent ? describePop(parent) : "patients in the cohort";
  const who = describePop(pop);
  const blocks: Block[] = [];

  if (mode === "percent") {
    blocks.push({
      kind: "metric",
      value: pctText(n, of),
      label: `of ${parent ? ofLabel : "the cohort"} ${n === 1 ? "is" : "are"} ${who}`,
      detail: `${n} of ${of}. ${basis(data.asof)}`,
    });
  } else {
    const whole = !parent && n === of;
    blocks.push({
      kind: "metric",
      value: String(n),
      label: whole ? "patients in the diabetes cohort" : who,
      detail: whole
        ? `Every patient with a diabetes diagnosis who was alive on the data date. ${basis(data.asof)}`
        : `${parent ? `Of ${of} ${ofLabel}` : `${pctText(n, of)} of ${of} patients in the cohort`}. ${basis(data.asof)}`,
    });
  }
  if (pop.status === "never" && n > 0) {
    blocks.push({ kind: "text", text: "\"Never tested\" means no A1c result appears in the available data, which may not hold a patient's complete history." });
  }
  // Open gaps in the pipeline's worklist order (as Care Gaps), then current
  // patients by MRN (as Patients).
  if (mode === "list" && n > 0) {
    const ordered = [...rows].sort((a, b) =>
      Number(a.priority ?? Infinity) - Number(b.priority ?? Infinity) || String(a.mrn).localeCompare(String(b.mrn)));
    blocks.push({ kind: "patients", ids: ordered.map((r) => String(r.patient_id)) });
  }
  if (n === 0) blocks.push({ kind: "text", text: "No patient in the cohort matches all of that." });
  const links = popLinks(pop);
  if (links.length) blocks.push({ kind: "links", links });

  const suggestions: string[] = [];
  if (mode !== "list" && n > 0) suggestions.push("Show them");
  if (!pop.seenMonths && n > 0) suggestions.push("How many of them were seen in the last 6 months?");
  suggestions.push("How did you calculate this?");
  blocks.push({ kind: "suggestions", items: suggestions.slice(0, 3) });

  return {
    blocks,
    ctx: {
      pop, parent, last: mode,
      method: method(pop, n, of, ofLabel, data.asof, data.rows.length),
      sql: popSql(pop, data.asof, mode === "list" ? "list" : "count"),
    },
  };
}

function groupAnswer(dimension: "age" | "setting", q: string, data: Data): Answer {
  const rows = dimension === "age" ? monitoringByAgeBand(data.rows) : monitoringBySetting(data.rows);
  const label = (k: string) => (dimension === "age" ? `Age ${BAND_LABEL(k as AgeBand)}` : settingLabel(k));
  const lowest = has(q, /\b(lowest|least|smallest|best)\b/);
  const eligible = rows.filter((r) => r.total >= SMALL);
  const pick = [...eligible].sort((a, b) => (lowest ? a.gapRate - b.gapRate : b.gapRate - a.gapRate) || b.total - a.total)[0];
  const small = rows.filter((r) => r.total > 0 && r.total < SMALL);
  const blocks: Block[] = [];
  if (pick) {
    blocks.push({
      kind: "metric",
      value: pctText(pick.gaps, pick.total),
      label: `${label(pick.key)} has the ${lowest ? "lowest" : "highest"} observed gap rate${small.length ? ` among groups with ${SMALL}+ patients` : ""}`,
      detail: `${pick.gaps} of ${pick.total} patients have an open A1c gap. ${basis(data.asof)}`,
    });
  }
  if (small.length) {
    const extreme = small.find((r) => (lowest ? r.gapRate === 0 : r.gapRate === 100));
    blocks.push({
      kind: "limitation",
      text: `${small.map((r) => `${label(r.key)} (${r.gaps} of ${r.total})`).join(", ")} ${small.length === 1 ? "has" : "have"} fewer than ${SMALL} patients, so ${small.length === 1 ? "its rate is" : "their rates are"} too unstable to rank.${extreme ? ` ${label(extreme.key)} shows ${pctText(extreme.gaps, extreme.total)}, but that is ${extreme.gaps} of ${extreme.total}.` : ""}`,
    });
  }
  blocks.push({ kind: "groups", dimension, rows, highlight: pick?.key, small: SMALL });
  blocks.push({ kind: "text", text: "This describes the data; a difference between groups does not show what causes it." });
  blocks.push({ kind: "links", links: [{ href: "/analytics", label: "View Analytics" }] });
  const pop: Pop = pick
    ? { ...ALL_PATIENTS, ...(dimension === "age" ? { band: pick.key as AgeBand } : { setting: pick.key }) }
    : ALL_PATIENTS;
  blocks.push({ kind: "suggestions", items: ["How many of them were seen in the last 6 months?", "Show their open gaps", "How did you calculate this?"] });
  return {
    blocks,
    ctx: {
      pop, last: "groups",
      method: [
        { label: "Population", value: `All ${data.rows.length} patients in the diabetes cohort, grouped by ${dimension === "age" ? "age band (18–44, 45–64, 65–75, 76+)" : "care setting of the last encounter"}.` },
        { label: "Gap rate", value: "Patients with an open A1c gap in the group, divided by all patients in the group." },
        { label: "Ranking", value: `Groups with fewer than ${SMALL} patients are shown but not ranked: one patient moves their rate too far.` },
        { label: "Definition", value: STATUS_DEFS.gap! },
      ],
      sql: dimension === "age"
        ? `SELECT CASE WHEN age < 45 THEN '18-44'\n            WHEN age < 65 THEN '45-64'\n            WHEN age <= 75 THEN '65-75'\n            ELSE '76+' END AS age_band,\n       count(*) AS patients,\n       count(*) FILTER (WHERE gap_flag) AS open_gaps,\n       round(100.0 * count(*) FILTER (WHERE gap_flag) / count(*), 1) AS gap_rate_pct\nFROM patients\nGROUP BY 1\nORDER BY 1`
        : `SELECT unit AS care_setting,\n       count(*) AS patients,\n       count(*) FILTER (WHERE gap_flag) AS open_gaps,\n       round(100.0 * count(*) FILTER (WHERE gap_flag) / count(*), 1) AS gap_rate_pct\nFROM patients\nGROUP BY 1\nORDER BY patients DESC, 1`,
    },
  };
}

function yearsAnswer(data: Data): Result {
  if (!data.history) return { needs: "history" };
  const tests = new Map<string, number>(), who = new Map<string, Set<string>>();
  let first = "", last = "";
  for (const [pid, d] of Object.entries(data.history)) {
    for (const p of d.a1c) {
      const y = p.d.slice(0, 4);
      tests.set(y, (tests.get(y) ?? 0) + 1);
      if (!who.has(y)) who.set(y, new Set());
      who.get(y)!.add(pid);
      if (!first || p.d < first) first = p.d;
      if (!last || p.d > last) last = p.d;
    }
  }
  if (!first) return { blocks: [{ kind: "text", text: "No A1c results are available." }], ctx: { last: "none" } };
  const rows = [];
  for (let y = Number(first.slice(0, 4)); y <= Number(last.slice(0, 4)); y++) {
    rows.push({ year: String(y), tests: tests.get(String(y)) ?? 0, patients: who.get(String(y))?.size ?? 0 });
  }
  const partial = [rows[0].year, rows[rows.length - 1].year];
  const full = rows.filter((r) => !partial.includes(r.year));
  const peak = full.reduce((a, b) => (b.tests > a.tests ? b : a), full[0] ?? rows[0]);
  const total = rows.reduce((n, r) => n + r.tests, 0);
  return {
    blocks: [
      { kind: "metric", value: total.toLocaleString("en-US"), label: "A1c results recorded", detail: `From ${longDate(first)} to ${longDate(last)}, in the synthetic records.` },
      { kind: "text", text: `Recorded testing rose from ${full[0]?.tests ?? 0} results in ${full[0]?.year ?? "—"} to a peak of ${peak.tests} in ${peak.year}. ${partial[0]} and ${partial[1]} are partial years: the history starts at the first result on file and stops at the data date, so their lower counts are coverage, not a fall in testing.` },
      { kind: "years", rows, partial },
      { kind: "links", links: [{ href: "/analytics", label: "View Analytics" }] },
      { kind: "suggestions", items: ["How did you calculate this?", "How many patients have never been tested?"] },
    ],
    ctx: {
      last: "years",
      method: [
        { label: "Population", value: `Every recorded A1c result for the ${data.rows.length} patients in the cohort.` },
        { label: "Counts", value: "Results recorded per calendar year, and separately the number of distinct patients with at least one result that year." },
        { label: "Partial years", value: `${partial[0]} begins at the first result on file; ${partial[1]} ends at the data date.` },
      ],
      sql: "-- The per-result A1c history is not in the patients view; it is the\n-- patient_detail export, counted per calendar year:\nSELECT year(observed_at) AS year,\n       count(*) AS a1c_results,\n       count(DISTINCT patient_id) AS patients_tested\nFROM a1c_observations\nGROUP BY 1\nORDER BY 1",
    },
  };
}

function patientAnswer(r: PatientRow, data: Data): Answer {
  const s = gapStatus(r);
  const v = lastA1cValue(r);
  const late = daysOverdue(r);
  const id = String(r.patient_id);
  const links = [{ href: `/patients/${encodeURIComponent(id)}/?from=ask`, label: "Open patient" }];
  if (s !== "current") links.push({ href: `/tasks?open=${encodeURIComponent(id)}`, label: "Review gap task" });
  return {
    blocks: [
      { kind: "patient", id },
      {
        kind: "text",
        text: s === "never"
          ? `No qualifying A1c result was found for MRN ${shortMrn(r)} in the available data, so the patient has an open gap.`
          : s === "overdue"
            ? `The most recent A1c in the available data is ${v?.toFixed(1)}% on ${longDate(String(r.last_a1c_date))}, ${late?.toLocaleString("en-US")} days past due.`
            : `The patient is current: an A1c result of ${v?.toFixed(1)}% on ${longDate(String(r.last_a1c_date))}.`,
      },
      { kind: "links", links },
    ],
    ctx: {
      patientId: id, last: "patient",
      method: [
        { label: "Record", value: `MRN ${shortMrn(r)} in the care-gap report, as of ${longDate(data.asof)}.` },
        { label: "Status", value: STATUS_DEFS[s === "current" ? "current" : s]! },
      ],
      sql: `SELECT *\nFROM patients\nWHERE mrn LIKE '${shortMrn(r)}%'`,
    },
  };
}

/* ------------------------------------------------------------- limits */

const LIMITS: { test: RegExp; text: string; suggest: string[] }[] = [
  {
    test: /\border(ed|s)?\b/,
    text: "The available source does not contain an orders table, so I cannot determine whether an A1c was ordered but not completed. A patient whose test was ordered and missed looks the same as one who was never sent for it.",
    suggest: ["Which patients have never had an A1c?", "Which patients are overdue?"],
  },
  {
    test: /\bdose|dosage|how much insulin|units of insulin|how many units\b/,
    text: "The dataset does not contain confirmed medication dose information. The medication records carry dispense (fill) counts, which are not doses and do not show what a patient takes. I can tell you whether an insulin prescription is documented.",
    suggest: ["How many patients have active insulin documented?"],
  },
  {
    test: /\b(should|recommend|advis|treat(ment)?|prescrib|titrat|diagnos|is it safe|ought to)\b/,
    text: "I can't give clinical advice. I report what the available data shows about A1c monitoring; what to do for a patient is a decision for a clinician with the full record.",
    suggest: ["Which patients have an open A1c gap?"],
  },
  {
    test: /\b(risk|urgen(t|cy)|sickest|high[- ]risk|most at risk|severity|priority score)\b/,
    text: "There is no risk or urgency score in this data, and I won't invent one. I can show which patients have never been tested, or who is most overdue.",
    suggest: ["Which patients are most overdue?", "Which patients have never had an A1c?"],
  },
  {
    test: /\b(control(led)?|uncontrolled|at goal|on target|below 7|above 7)\b/,
    text: "This assistant reports whether A1c is being monitored, not whether results are at goal. Individual A1c goals differ, and the app does not classify patients as controlled or uncontrolled.",
    suggest: ["How many patients are current?", "What is the gap rate by age band?"],
  },
  {
    test: /\b(colonoscop|mammogra|cholesterol|lipid|blood pressure|vaccin|immuni[sz]|smoking|bmi|weight|allerg|readmission)\b/,
    text: "That isn't in the data this assistant reads. It answers questions about the diabetes cohort's A1c monitoring and testing.",
    suggest: ["How many patients are in the cohort?"],
  },
  {
    test: /\b(address|phone|email|contact details|next of kin|ssn|social security|name of)\b/,
    text: "The source holds no contact or identifying details beyond a record number, so there is nothing to show.",
    suggest: [],
  },
  {
    test: /\b(task|outreach|contacted|called|reached|scheduled|appointment|follow[- ]?up)\b/,
    text: "Follow-up tasks are application workflow data saved in your browser, not part of the clinical source, so I don't answer from them. The Tasks page shows them.",
    suggest: [],
  },
];

/* ---------------------------------------------------------------- entry */

const SUGGEST_START = [
  "How many patients currently have an open A1c gap?",
  "Which patients have never had an A1c?",
  "Which age group has the highest gap rate?",
  "Show patients with an open gap who were seen in the last 6 months",
];

export function answer(question: string, ctx: Ctx, data: Data): Result {
  const q = question.toLowerCase().replace(/\s+/g, " ").trim();
  if (!q) return { blocks: [], ctx };

  // Statements that would change data are refused outright: Ask AI is
  // read-only, and a word like "patients" in them must not be read as a
  // question about the cohort.
  if (has(q, /^(delete|update|insert|drop|alter|create|truncate|replace|merge|attach|copy|grant)\b/)) {
    return {
      blocks: [{ kind: "limitation", text: "Ask AI is read-only. It can run a SELECT statement to check an answer, but nothing that changes data." }],
      ctx: { ...ctx, last: "none" },
    };
  }

  // Explain the previous answer.
  if (has(q, /\b(sql|query)\b/)) {
    if (!ctx.sql) return say("Ask a question first, and I can show the query behind the answer.", ctx);
    return {
      blocks: [
        { kind: "text", text: "This is the query equivalent to the last answer, against the patients view of the care-gap report:" },
        { kind: "sql", sql: ctx.sql, note: "It returns the same result as the answer above." },
      ],
      ctx: { ...ctx, last: "explain" },
    };
  }
  if (has(q, /how did you (calculate|get|work|compute|count|figure)|how was (this|that) calculated|explain (that|this|your|the) (answer|number|calculation|result)|what('s| is) (the )?(method|methodology|definition)|where does (this|that) come from/)) {
    if (!ctx.method) return say("Ask a question first, and I can explain how the answer was worked out.", ctx);
    return {
      blocks: [{ kind: "method", items: ctx.method }, { kind: "suggestions", items: ["Show me the SQL"] }],
      ctx: { ...ctx, last: "explain" },
    };
  }

  // Limitations and refusals, before anything is matched to data.
  for (const l of LIMITS) {
    if (l.test.test(q)) {
      return {
        blocks: [{ kind: "limitation", text: l.text }, ...(l.suggest.length ? [{ kind: "suggestions" as const, items: l.suggest }] : [])],
        ctx: { ...ctx, last: "none" },
      };
    }
  }

  // A specific patient by MRN prefix.
  const mrn = q.match(/\b(?:mrn\s*)?([0-9a-f]{6,8})\b/);
  if (mrn) {
    const r = data.rows.find((x) => String(x.mrn).toLowerCase().startsWith(mrn[1]));
    if (r) return { ...patientAnswer(r, data), title: `Patient ${shortMrn(r)}` };
  }

  // Testing over time.
  if (has(q, /(testing|tests|a1c results?|a1cs) (changed|over time|per year|by year|trend)|over time|by year|per year|trend/)) {
    const res = yearsAnswer(data);
    return "needs" in res ? res : { ...res, title: "A1c testing over time" };
  }

  // Group comparisons.
  const byAge = has(q, /age (group|band)s?|by age|which ages?/);
  const bySetting = has(q, /(care )?settings?|by unit|which units?|locations?/) && !SETTING_WORDS.some(([re]) => re.test(q));
  if ((byAge || bySetting) && has(q, /highest|lowest|most|least|rate|compare|breakdown|by |which|best|worst/)) {
    return { ...groupAnswer(byAge ? "age" : "setting", q, data), title: byAge ? "Gap rate by age band" : "Gap rate by care setting" };
  }

  // Most overdue.
  if (has(q, /most overdue|longest overdue|overdue the longest|longest since/)) {
    const rows = sortPatients(data.rows.filter((r) => daysOverdue(r) !== null), "overdue");
    return {
      blocks: [
        { kind: "metric", value: String(rows.length), label: "patients have an earlier A1c that is now overdue", detail: `Most overdue first. Patients with no A1c at all have no due date to be late against and are not in this list. ${basis(data.asof)}` },
        { kind: "patients", ids: rows.map((r) => String(r.patient_id)) },
        { kind: "links", links: [{ href: "/care-gaps?status=overdue", label: "View all in Care Gaps" }] },
        { kind: "suggestions", items: ["Which patients have never had an A1c?"] },
      ],
      ctx: { pop: { ...ALL_PATIENTS, status: "overdue" }, last: "list", method: method({ ...ALL_PATIENTS, status: "overdue" }, rows.length, data.rows.length, "patients in the cohort", data.asof, data.rows.length), sql: popSql({ ...ALL_PATIENTS, status: "overdue" }, data.asof, "list").replace("ORDER BY priority NULLS LAST, mrn", "ORDER BY days_overdue DESC") },
      title: "Most overdue patients",
    };
  }

  // Populations: new, or narrowing the last one.
  const mods = parsePop(q);
  const follow = isFollowUp(q) && ctx.pop;
  const mode: "count" | "list" | "percent" =
    has(q, /percent|percentage|share|proportion|what fraction|what part/) ? "percent"
      : has(q, /how many|number of|count|total/) ? "count"
        : has(q, /\b(which|who|list|show|display|give me|see)\b/) ? "list"
          : follow && ctx.last === "list" ? "list" : "count";

  const mentionsCohort = has(q, /cohort|patients|people|population|diabet/);
  if (Object.keys(mods).length === 0 && !follow && !mentionsCohort) {
    return {
      blocks: [
        { kind: "text", text: "I can't answer that from the data I have. I answer questions about the diabetes cohort's A1c monitoring: who has an open gap, who has never been tested, how groups compare, how testing has changed over time, and individual patients by MRN." },
        { kind: "suggestions", items: SUGGEST_START.slice(0, 3) },
      ],
      ctx: { ...ctx, last: "none" },
    };
  }

  if (follow) {
    const base = ctx.pop!;
    // "Show their open gaps" / "how many of them..." keeps the previous
    // population and adds whatever the follow-up names.
    const pop: Pop = { ...base, ...mods };
    const narrowed = JSON.stringify(pop) !== JSON.stringify(base);
    const res = populationAnswer(pop, mode, data, narrowed ? base : ctx.parent);
    // After a group answer, "them" is the whole group; also say how many of
    // its open gaps the filter keeps, since that is usually the next question.
    if (ctx.last === "groups" && narrowed && pop.status === "all") {
      const gaps = popRows(data.rows, { ...pop, status: "gap" }, data.asof).length;
      const allGaps = popRows(data.rows, { ...base, status: "gap" }, data.asof).length;
      res.blocks.splice(1, 0, { kind: "text", text: `Of the ${allGaps} with an open A1c gap, ${gaps} ${gaps === 1 ? "was" : "were"}.` });
    }
    return res;
  }

  const pop: Pop = { ...ALL_PATIENTS, ...mods };
  const res = populationAnswer(pop, mode, data, undefined);
  return { ...res, title: titleFor(pop, mode) };
}

function say(text: string, ctx: Ctx): Answer {
  return { blocks: [{ kind: "text", text }], ctx };
}

/** A short conversation title from the first question's population. */
function titleFor(p: Pop, mode: "count" | "list" | "percent"): string {
  const base: Record<StatusFilter, string> = {
    all: "Cohort size", current: "Current patients", gap: "Open A1c gaps",
    never: "Never-tested patients", overdue: "Overdue patients",
  };
  let t = base[p.status];
  if (p.status === "all" && (p.band !== "all" || p.setting !== "all" || p.insulin !== "all" || p.seenMonths)) t = "Patients";
  if (p.band !== "all") t += ` aged ${BAND_LABEL(p.band)}`;
  if (p.setting !== "all") t += `, ${settingLabel(p.setting).toLowerCase()}`;
  if (p.insulin === "yes") t += " on insulin";
  if (p.seenMonths) t += ", seen recently";
  if (mode === "percent") t = `Share: ${t.toLowerCase()}`;
  return t;
}

