/**
 * FR7: the synthetic-data notice appears on every page, including error states.
 * It lives in the root layout rather than in any page, so it cannot go missing
 * from the one page someone screenshots.
 */
export default function Banner() {
  return (
    <div
      className="w-full border-b px-4 py-2 text-center text-sm"
      style={{ background: "var(--orange-wash)", borderColor: "var(--rule)", color: "var(--ink)" }}
    >
      <strong>Synthetic data only.</strong> Every patient here was generated by
      Synthea. No real patient information is involved, and nothing on this site
      is a medical record.
    </div>
  );
}
