"use client";

import { Info } from "lucide-react";

import { cn } from "cn";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

/**
 * The synthetic-data notice, made quiet but kept universal.
 *
 * It used to be a full-width red band above every page (FR7), which kept it on
 * every screenshot and every 404 but shouted over the care work on every page.
 * It is now one badge in the global header, which renders on every route
 * including not-found and error, at every width, with the sidebar open, closed
 * or collapsed to icons. A second copy beside the product name was tried and
 * removed: two warnings on one screen is the shouting again, in miniature.
 *
 * The badge text says what matters on its own. The tooltip adds detail and is
 * never the only place the fact appears.
 */
export function SyntheticDataBadge({ className }: { className?: string }) {
  return (
    <Tooltip>
      <TooltipTrigger
        render={
          <button
            type="button"
            className={cn(
              "inline-flex shrink-0 items-center gap-1 rounded-md border border-status-warning/30",
              "bg-status-warning/10 px-1.5 py-0.5 text-xs font-medium text-status-warning",
              "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring",
              className,
            )}
          />
        }
      >
        <Info className="size-3" aria-hidden />
        Synthetic data
      </TooltipTrigger>
      <TooltipContent className="max-w-64 text-xs leading-relaxed">
        This demonstration uses synthetic patient data generated by Synthea. No
        real patient information is displayed.
      </TooltipContent>
    </Tooltip>
  );
}
