import type { Metadata } from "next";
import { AppSidebar } from "@/components/shell/AppSidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Clinical Care Gap Explorer",
  description:
    "Finds diabetic patients overdue for an A1c test, and shows the data quality work required before that list can be trusted. Synthetic data only.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* FR7: the synthetic-data notice sits above the shell, so it is on every
            page including 404s and error states — it cannot go missing from the
            one page somebody screenshots. */}
        <div className="border-b bg-destructive/10 px-4 py-1.5 text-center text-xs">
          <strong className="font-semibold">Synthetic data only.</strong>{" "}
          Every patient here was generated by Synthea. No real patient
          information is involved.
        </div>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset className="min-w-0">{children}</SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
