import Link from "next/link";

import { Page, Section } from "@/components/shell/Page";

export const metadata = { title: "Help" };

const linkCls =
  "rounded-sm font-medium text-primary hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring";

/** Short, and only things that are true today. */
export default function HelpPage() {
  return (
    <Page
      title="Help"
      description="What this application is, how to get around it, and where the data comes from."
    >
      <Section title="What this is">
        <p className="max-w-3xl text-sm leading-relaxed">
          Care Gap Explorer finds patients with diabetes who have gone more than
          twelve months without an A1C test, so that someone can follow up. It is a
          demonstration: every patient is synthetic, generated by Synthea, and no
          real patient information appears anywhere.
        </p>
      </Section>

      <Section title="Getting around">
        <ul className="flex max-w-3xl list-disc flex-col gap-2 pl-5 text-sm leading-relaxed">
          <li>
            <strong className="font-medium">Care Operations</strong> is the day-to-day
            work: who needs attention and what to do about them.{" "}
            <Link href="/patients" className={linkCls}>Patients</Link> is the place to
            start today.
          </li>
          <li>
            <strong className="font-medium">Insights</strong> covers the population as a
            whole, and <Link href="/ask" className={linkCls}>Ask AI</Link> answers
            questions about the cohort in plain words, and explains any answer on request.
          </li>
          <li>
            <strong className="font-medium">Data &amp; Quality</strong> is how the data
            was checked before any of it reached a list.
          </li>
          <li>
            Press <kbd className="rounded border bg-muted px-1 font-mono text-xs">⌘B</kbd> or{" "}
            <kbd className="rounded border bg-muted px-1 font-mono text-xs">Ctrl B</kbd> to
            collapse the sidebar. From the top of any page, the first Tab reaches a
            Skip to content link.
          </li>
        </ul>
      </Section>

      <Section title="Learning more">
        <p className="max-w-3xl text-sm leading-relaxed">
          <Link href="/learn" className={linkCls}>Learn</Link> collects the background:
          what an A1C measures, why a missed test matters, and what this data can and
          cannot tell you. The source and the decisions behind it are{" "}
          <a
            href="https://github.com/Franklin0603/clinical-care-gap-explorer"
            className={linkCls}
            target="_blank"
            rel="noreferrer"
          >
            on GitHub
          </a>
          .
        </p>
      </Section>
    </Page>
  );
}
